### ISSUE TITLE
502 caused by large file

### ISSUE THREAD

**Issue by magic282** [lrsjng/h5ai#415]
I downloaded a debian DVD iso under the foler, and it's 1.7 GB. After that, the h5ai shows 502 error. It recovers after I removed the big file.

**Comment by lrsjng** [comment]
@magic282 anything in the PHP log files?

**Comment by hpp3** [comment]
I got this bug as well, and I resolved it. The bug is in the code that computes filesize, in class-util.php. If you are on 64 bit system, the code calls filesize() to compute filesize. Otherwise, I think it does some kind of binary search to find the filesize. The bug is in the search code. On sufficiently large files, this part never terminates. You can either figure out what the logic is and fix it, or a workaround is to just delete this part and make it always use filesize().

**Comment by magic282** [comment]
Merge this issue to [issue 455](https://github.com/lrsjng/h5ai/issues/445).
