### ISSUE TITLE
Add image dimensions

### ISSUE THREAD

**Issue by XhmikosR** [lrsjng/h5ai#426]
Having image dimensions prevents the browser from resizing content since it knows beforehand the size of the image.

**Comment by lrsjng** [comment]
I use the page speed insight tools myself.. all images should be clipped anyway, so no harm here..

**Comment by XhmikosR** [comment]
Are we going to have the same thing here?

**Comment by XhmikosR** [comment]
It's proven. Period.

You don't want to do it, say so. But don't try to find other reasons for sticking to your wrong choice.

**Comment by lrsjng** [comment]
The width and height should be specified for all images in the style sheets. I might have missed some, but that shouldn't be the case. If you find images, please let me know, and I'll fix it if it is fixable. What I'm avoiding is settings `width` and `height` attributes itself in the `<img>` tags, since this would add significant JS code with near zero improvement.

**Comment by lrsjng** [comment]
thought so
