### ISSUE TITLE
PDF thumbnails don't work.

### ISSUE THREAD

**Issue by coltondrg** [lrsjng/h5ai#429]
I am running h5ai 0.27.0 on Arch Linux

PDF thumbnails are not working at all. They are enabled in the configuration file, and the server info page says that the command is available.

Server information is as follows:
http://192.168.0.3/_h5ai/
h5ai version - 0.27.0
Index file found - yes
Options parsable - yes
Types parsable - yes
Server software - apache 2.4.12
PHP version - 5.6.6
Cache directory - yes
Image thumbs - yes
Use EXIF thumbs - yes
Movie thumbs - yes
PDF thumbs - yes
Shell tar - yes
Shell zip - yes
Shell du - yes

Thumbnails section of config file is:
    "thumbnails": {
        "enabled": true,
        "img": ["img-bmp", "img-gif", "img-ico", "img-jpg", "img-png"],
        "mov": ["vid-avi", "vid-flv", "vid-mkv", "vid-mov", "vid-mp4", "vid-mpg", "vid-webm"],
        "doc": ["x-pdf", "x-ps", "x-doc"],
        "delay": 1,
        "size": 240,
        "exif": true
    },

Any ideas as to what is wrong?

**Comment by lrsjng** [comment]
@ColtonDRG did you try it with "x-doc" removed from `thumbnails.docs` section?

**Comment by ColtonDRG** [comment]
@lrsjng Yes, it makes no difference.

**Comment by lrsjng** [comment]
@ColtonDRG anything the PHP error logs?

**Comment by 52M** [comment]
@ColtonDRG hi,I running h5ai on Ubuntu but PDF thumbs - no Movie thumbs - no. how I should do? Anyway thanks a lot.

**Comment by lrsjng** [comment]
@52M I don't think that `yum` is the right command on a Ubuntu distro. `yum` sound more like Fedora/Red Hat.. are you sure you installed ffmpeg and ImageMagick correctly?

**Comment by 52M** [comment]
Sure, this is wrong commands on Ubuntu.And that is not my question and I was asked by someguy. h5ai is a awesome web server.

**Comment by RomeSilvanus** [comment]
I have a similar problem with some PDF files. In some cases it will generate the thumbnails for a bunch of them but then leave out a few. And everytime I reopen the directory I can see the 'convert' process (in htop) trying to generate thumbnails again. 

Maybe there is something wrong with the PDF files, but I wouldn't know how to check this up. Is there a way to maybe see the output of convert to check for errors?

I can live with a few PDFs not having a thumbnail, but this is especially a problem since the thumbnail generating locks up the php processor and gives a 504 when trying to switch directories while it's running.

Example where you can see two of the PDFs not getting a thumbnail: 
![http://i.imgur.com/nlgf9RQ.jpg](http://i.imgur.com/nlgf9RQ.jpg)



Also something more unrelated, sometimes some images/PDFs get blank (completely white/black) preview images. Images that have a transparent background and only the colour white are also quasi invisible on the h5ai background.

**Comment by lrsjng** [comment]
the command is one of those:

  * `convert -density 200 -quality 100 -strip in.pdf[0] out.jpg`
  * `gm convert -density 200 -quality 100 in.pdf[0] out.jpg`

depends on what command is found.

replace `in.pdf` with your PDF file

**Comment by RomeSilvanus** [comment]
The output I got back:
* convert -density 200 -quality 100 -strip in.pdf[0] out.jpg
* gm convert -density 200 -quality 100 in.pdf[0] out.jpg
* Running Ghostscript directly (gs -sDEVICE=pngalpha -sOutputFile=cover.png -r144 file.pdf)
![link](http://i.imgur.com/5NgOfdH.png)

What is running when opening the folder:
![link](http://i.imgur.com/DjYDPCm.png)

At first I tried to Google the error message (Error: /rangecheck in resolveR) which led me [to the following Stackoverflow page](http://stackoverflow.com/questions/11677854/imagemagick-convert-error-rangecheck-in-resolver-with-pdfs-larger-than-600kb) suggesting to either [use a newer version of Ghostscript or try to open the PDF with Ghostscript directly](http://stackoverflow.com/a/11678082) to see if GS itself has a problem with it.

The Ghostscript version I found out with `gs -v` which gave me GPL Ghostscript 9.18 (which is the version that comes with Ubuntu 16.04). I then proceeded to install version [9.19 for the next Ubuntu version from Launchpad](https://launchpad.net/ubuntu/yakkety/amd64/ghostscript/9.19~dfsg+1-0ubuntu1) which, while giving me a more current GS version, did not lead to any improvement.

After half an hour of trying I found the reason: Apparently the PDF files are corrupted or non-standard in some way. Preview.app on OSX can't open it. I actually never tried to open all the files locally. Though for some reason viewing them on the Dropbox website works without a problem (which is how I checked if they worked first). ![link](http://i.imgur.com/w0hYuJK.jpg)
So I'm not sure what they do different here. I can't try it on Adobe Reader since I don't have it installed. Cloudconvert.com also can't fix them.

Trying to fix them with GS also failed (gs -o repaired.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress corrupted.pdf also failed and gave the same error as in the screenshot above.

So I guess this problem can be disregarded until I find some way to repair them (or find another version).

I also found out why some other PDFs didn't get thumbnail. They had a : in their filename (which OSX does not care for). Thought running the commands you suggested on them manually actually created the image files, so I'm not sure what else could be wrong here. I'll just change the filename for now.

This has drifted off-topic a bit so I'll stop now.

**Comment by Celti** [comment]
> So I guess this problem can be disregarded until I find some way to repair them (or find another version).

Install `mutool` (part of [MuPDF](http://mupdf.com/)) and run `mutool clean <input.pdf> <output.pdf>`. Has never failed to fix a broken PDF for me, even weird and shonky Quartz crap, badly malformed headers, and such.

**Comment by RomeSilvanus** [comment]
Sadly this did not work also, it just repeats an error:
`error: expected object number `
`error: expected object number`
`error: Repair failed already - not trying again`
`error: cannot parse object (38 0 R)`
`error: cannot load object (38 0 R) into cache`
`warning: cannot load object (38 0 R) into cache`
`error: expected object number`


I just have to accept that the PDF really is that broken and find a new one. Still weird that Dropbox can read it though.

**Comment by lrsjng** [comment]
@RomeSilvanus is your site public? just got interested in the content..

**Comment by RomeSilvanus** [comment]
@lrsjng Which content are you interested in?

Let me say it like this: Depending on where you are in the world it shouldn't be public. Depending on what your tastes are it shouldn't be public. Depending on how fast you get offended it shouldn'T be public. It's a big bunch of safe to kinky files, different fandoms, and different content.

Though it's as public as it gets when you know the subdomain for it, there's no password on it.

Though if you're interested in the Dungeons & Dragons stuff I can give you the URL of the Mega.nz folder I got it from.

**Comment by lrsjng** [comment]
@RomeSilvanus yeah, just the D&D stuff, never heard of White Dwarf..

**Comment by RomeSilvanus** [comment]
@lrsjng It's a pretty old magazine series.

http://pastebin.com/eVnqh9rp
Here you can find White Dwarf and a bunch of other DnD stuff.

**Comment by palto42** [comment]
I also had issues with PDF thumbnail generation and  finally found that it was caused by the new ImageMagic security policies which by default disabled PDF processing. In Ubuntu/Debian the file `/etc/ImageMagick-6/policy.xml` has to be configured to re-enable PDF read (write not needed for this purpose, e.g. set  `<policy domain="coder" rights="read" pattern="PDF" />`
See also https://imagemagick.org/script/security-policy.php

**Comment by sadajun916** [comment]
@palto42 

Thank you!
PDF thumbnail generation works fine on my computer thanks to your comment.
