### ISSUE TITLE
Setting a document root folder

### ISSUE THREAD

**Issue by alexge233** [lrsjng/h5ai#437]
Hello!

Great job, love the library.
I am however, puzzled by something: I want to set a specific folder, as the root directory.
I've placed the contents of _h5ai into: $ROOT/php/packager/server/php/index.php
I disabled directory browsing, and want to show ONLY a specific folder. The reason is that I intend to create (via PHP) on the spot random-named folders, for users to upload files and directories.

What I now get, is the entire tree: php->packager->server->php
which is not what I want.

Is there some way to (a) disable this behavior? I've looked into options.json, but none of the options seem to support this, and (b) either set a specific folder as the root one (e.g., I will create a new folder /php/packager/random-uuid-v4/ and I would like h5ai to show only that folder, and nothing else. If the user creates a sub-folder in it, so be it.

Many thanks in advance

**Comment by lrsjng** [comment]
@alexge233 if you place the folder `_h5ai` (not it's content, but the whole folder) in any subfolder that subfolder will be considered as root.

For example place `_h5ai` in `$ROOT/some/folder/` so that it's location is `$ROOT/some/folder/_h5ai` then `$ROOT/some/folder/` will be considered as root for displaying files. You have to add `/some/folder/_h5ai/server/php/index.php` to your directory index in this subfolder.

**Comment by redline-dev** [comment]
Woah just what I looking for. Thanks!
