### ISSUE TITLE
Piwik tracking not working

### ISSUE THREAD

**Issue by florianbeer** [lrsjng/h5ai#438]
It seems h5ai is requesting `piwik.js` from my server but never actually fires the tracking request (verified by watching `access.log` for my Piwik installation). There are no visits counted in the Piwik webinterface.
Chrome doesn't show any errors but Safari reports the following in the Console:
```
[Error] ReferenceError: Can't find variable: Piwik
	(anonymous function) (scripts.js, line 12)
	dispatch (scripts.js, line 3)
	handle (scripts.js, line 3)
```

**Comment by ThaDafinser** [comment]
Got the same issue `piwik.js` is loaded, but no tracking at all. 

Why it was closed?

**Comment by ThaDafinser** [comment]
Compiled the JS looks like this `load()` will never get called (tried it with console.log)
```js
modulejs.define("ext/piwik-analytics",["_","$","core/settings"],
	function(e,t,n){
		function r(){
			if(i.enabled){
			
			var e=("https:"===document.location.protocol?"https://":"http://")+i.baseURL+"/";
			t("<script/>").attr("src",e+"piwik.js").appendTo("body"),
			
			t(window).load(function(){
				var t=Piwik.getTracker(e+"piwik.php",i.idSite);
				
				t.trackPageView(),
				t.enableLinkTracking()}
			)}
		}
	
		var i=e.extend({enabled:!1,baseURL:"not-set",idSite:0},n["piwik-analytics"]);r()
	}
),
```

**Comment by lrsjng** [comment]
@ThaDafinser please check if one of the latest [dev builds](https://release.larsjung.de/h5ai/develop/) works for you..

**Comment by ThaDafinser** [comment]
In the latest dev-build piwik.js does not load and since it does not load this error msg come up.
![image](https://cloud.githubusercontent.com/assets/533017/17355652/66b68dbc-5952-11e6-8b46-3c40bd151f79.png)

@lrsjng it seems that the `dom` part was recently removed?
https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/public/js/lib/ext/piwik-analytics.js#L22
https://github.com/lrsjng/h5ai/commit/901d8c407dfbd0c730487809302f7ffe03284306#diff-470cdfe33c33f9397c60959631d115b5L2

**Comment by twwd** [comment]
I have the same problem that piwik.js is loaded but no tracking, also tried the latest dev version.

**Comment by ThaDafinser** [comment]
@lrsjng shall we create a new ticket for this?

**Comment by praesidenzfall** [comment]
simple fix. add the Matomo tracking code before the closing </head>-tag in the file
`/_h5ai/private/php/pages/index.php`
