### ISSUE TITLE
max thumbnails number in a folder

### ISSUE THREAD

**Issue by obayemi** [lrsjng/h5ai#506]
Hi, I use h5ai to make a photo gallery, but when it doesn't show thumbnail past 125 images, but I can't find anything about it in the config, in your issues, or on google.
Is it an intended feature to prevent overloading the server? and would it be possible to make it display every thumbnails?
thanks!

**Comment by SushiDude** [comment]
I am also encountering this issue. Upon viewing a directory, h5ai makes a POST request for at max 250 thumbnail images. Since there are two thumbnails per file, it only displays them for 125 files. However, I am not sure of where this limit is being enforced.

**Comment by obayemi** [comment]
not bad, didn't think of checking the post request. but I don't see where that limit is set either...

**Comment by RomeSilvanus** [comment]
I'm also interested in this. I have folders that range from 5 to over 5000 files. Either I need to refresh the page a few dozen times until it loads them, or sometimes the whole php-fpm process dies and I need to restart it completely.

**Comment by jobenvil** [comment]
@RomeSilvanus can you post your php-fpm configuration regarding timeouts? I did modify something and now it doesn't refresh anymore, but the php-fpm5 process increases and then sudenly appears the timeout.

**Comment by RomeSilvanus** [comment]
@jobenvil Here it is: http://pastebin.com/7Qavq0Tw 
Mind that I have practically have no experience with PHP.

I did modify "max_execution_time" to 300, after running with the standard settings for a some time to see if anything changes. Nothing changed.
I also set "memory_limit = 256M" (was 64M) (Server has ~ 5GB)

As I said, folders with a few hundred (<1000) pictures load sometimes when I keep refreshing the page after the php5-fpm process stops working. Bigger folders don't really generate any thumbnails at all. I've seen installations where there were folders with a few thousand pictures and they did load find. So I'm not sure if it maybe requires nearly a supercomputer to work at that amount of files, or if I set something wrong.

**Comment by jobenvil** [comment]
@RomeSilvanus Thanks!, Your server should be able to manage it. No, there is no necessity of a supercomputer (funny ;-) it is in my opinnion a tunning feature between nginx and php-fpm *.ini config files. I got running before h5ai fine, be able to see all the thumbnails (each picture about 1,5 MB) , but because I was playing with config files and tunning I breaked it ( I discovered this last week) and I started to try to repair it. Unfortunately I have another services running on the server and maybe if I fix the h5ai I will break the other services that depends also in timeouts. The other point is to check what kind of memcached you have running. I'm running on a BananaPro (1GB RAM) + nginx 1.9.* + debian Testing/Stretch

If I get this running again I will inform you what did the trick again. There is a lot of *.ini files regarding tunning inside php-fpm...

Once again, thank you for the pastebin!

**Comment by RomeSilvanus** [comment]
@jobenvil 
"dpkg -l | grep memcache" gives me the following. Not sure if that's what you wanted to know.
ii  libmemcached10:amd64   1.0.8-1ubuntu2   amd64   C and C++ client library to the memcached server
ii  memcached   1.4.14-0ubuntu9   amd64   A high-performance memory object caching system
ii  php5-memcached   2.1.0-6build1   amd64   memcached extension module for PHP5, uses libmemcached


But please do and tell if you find out anything regarding all this!

**Comment by obayemi** [comment]
@SushiDude If still interrested, I spend hours tracking the variables states to find where this value was enforced, and it is actually... a php configuration!
http://php.net/manual/en/info.configuration.php#ini.max-input-vars

Since there is 4 variables for each thumbnail request in the array (type, href, width, height), the default value of 1000 max variables can't alow a request for more than 250 images (therefore no thumbnails for more than 125 images).
You can just increase it in your php.ini and it will work fine! (I have put 10000 instead)

**Comment by RomeSilvanus** [comment]
@obayemi I'm sorry to kinda reopen this, but does this solution actually work for you? Does it display more thumbnails now?

Because for me there was no change in the number of thumbnails generated, regardless of what number I put in.

**Comment by RomeSilvanus** [comment]
Nevermind, I was using the wrong php.ini

/etc/php5/cli/php.ini
instead of 
/etc/php5/cgi/php.ini

**Comment by SushiDude** [comment]
@obayemi Thanks for the information. However, you should not close this issue; the solution is not obvious and should not be necessary.

https://github.com/lrsjng/h5ai/issues/283 and https://github.com/lrsjng/h5ai/issues/266 should be implemented to resolve this issue.

**Comment by obayemi** [comment]
Well... It's not a h5ai issue finally. And that is the only thing that was blocking the reception of a large number of thumbnails...

-------- Original Message --------

**Comment by RomeSilvanus** [comment]
I just want to add to this one more time. I recently installed the Beta 2 of Ubuntu Server 16.04 to test it out, but instead of php-fpm I used HHVM (Hip-Hop Virtual Machine). It's not only faster and uses less resources but also displays all thumbnail in a folder with a few thousand images without any problems. Unlike php-fpm.

So everyone looking for a fast solution could try switching to HHVM.
