### ISSUE TITLE
Stream FLAC

### ISSUE THREAD

**Issue by PixiBixi** [lrsjng/h5ai#531]
Hi, is it possible to stream FLAC with h5ai ?

If yes, please explain me how :)

Thanks!

**Comment by Draxter** [comment]
To do that, I think you need to set up your web server to serve the flac mime type (audio/flac) correctly.

**Comment by MechMK1** [comment]
This has nothing to do with h5ai. "Streaming" a file is nothing else than downloading and then not saving it, so the webserver has very little they can do about it.

If you want your browser to be able to play .flac files, open a feature request for your respective browser.

Otherwise, you can always stream the file via HTTP(S) and VLC.

**Comment by da3dsoul** [comment]
It works in chromium at least. I've got it working on Desktop (Windows) and mobile (Android)
