### ISSUE TITLE
Tree view incorrectly moves folder to a child folder

### ISSUE THREAD

**Issue by Scrxtchy** [lrsjng/h5ai#533]
Updated to the latest version last night,
Noticed that this strange behaviour was occurring
Only affects the next directory from the parent's directory and moves it in as a child.
Also only affects the selected folder in the main view

If the broken folder is expanded, all the child directories are displayed on the same level as the broken folder

![](https://jii.moe/E1yUu7-M-.gif)

**Comment by vdhatterwal** [comment]
It seems the bug is still there. I did the following:
 * downloaded the latest version 0.28.1 (from your homepage) **several times**
![2capture](https://cloud.githubusercontent.com/assets/6457168/17203460/4d1ca402-54bd-11e6-9283-70b5aad358dd.PNG)
 * deleted previous files (even options and config files)
 * cleared cache of my browser
 * even tried it in private browsing

![c3apture](https://cloud.githubusercontent.com/assets/6457168/17203475/6305acf0-54bd-11e6-86b9-0667422f7876.PNG) ![capture](https://cloud.githubusercontent.com/assets/6457168/17203476/63096cb4-54bd-11e6-83a8-7721e2e51f6f.PNG)

I even downloaded it from git repo (but I couldn't even run after downloading from GitHub: got 403)
FYI, I'm using latest Firefox on Windows 10.

I don't know why, but the change log shows 0.28.0 and no heading with 0.28.1
![suntitled](https://cloud.githubusercontent.com/assets/6457168/17203495/77d8a25e-54bd-11e6-8bc0-b7d56c38b267.png)

**Comment by lrsjng** [comment]
@vdhatterwal have a here https://release.larsjung.de/h5ai/develop/

**Comment by vdhatterwal** [comment]
Thank you very much for the quick reply. I tried two(003 and 133) of those and the second one(https://release.larsjung.de/h5ai/develop/h5ai-0.28.1%2B133~0315e29.zip) did the trick. It is working perfectly now.
![untitleds](https://cloud.githubusercontent.com/assets/6457168/17210432/937cd868-54e0-11e6-9776-e4ce5a8de3d6.png)

**Comment by lrsjng** [comment]
was fixed in +027
