### ISSUE TITLE
Unable to download the text file

### ISSUE THREAD

**Issue by iflei** [lrsjng/h5ai#569]
I uploaded a text file, is unknown file format. I want to download this file, But it will automatically open the file to the browser. I add the file type to "types.json". In the  "ar-zip"  list.  But I still couldn't download this text files.

**Comment by lrsjng** [comment]
I not sure that I understand what you expect to happen.. that seems to be the default behavior of the browser, that kicks in. If the file is open in the browser most browsers support a right click and `save as...` functionality

**Comment by dionrhys** [comment]
To force the browser to download the files when you click them, you need to configure your web server to send a `Content-Disposition` HTTP header when serving your text files.

Here is an example for nginx (untested):
```
location ~* /([^"/]+\.txt)$ {
    add_header Content-Disposition 'attachment; filename="$1"';
}
```
The example above would affect all URLs under `/` so be wary of that. It shouldn't affect h5ai because it filters for `.txt` files specifically.
